In [1]:
import cv2

def read_img(path):
    img = cv2.imread(path)
    return type(img), img.shape, img

if __name__ == '__main__':
    path = './data/img1.jpg'
    img_type, img_shape, img = read_img(path)
    print('img_type: {}'.format(img_type))
    print('img_shape: {}'.format(img_shape))
    print('img: {}'.format(img))

img_type: <class 'numpy.ndarray'>
img_shape: (1600, 2560, 3)
img: [[[224 200 176]
  [224 200 176]
  [224 200 176]
  ...
  [212 178 149]
  [212 178 149]
  [212 178 149]]

 [[224 200 176]
  [224 200 176]
  [224 200 176]
  ...
  [213 179 150]
  [213 179 150]
  [213 179 150]]

 [[224 200 176]
  [224 200 176]
  [224 200 176]
  ...
  [214 180 151]
  [215 181 152]
  [215 181 152]]

 ...

 [[ 30  28  28]
  [ 34  32  32]
  [ 41  39  39]
  ...
  [ 14  13  15]
  [ 10   9  11]
  [  8   7   9]]

 [[ 33  31  31]
  [ 34  32  32]
  [ 36  34  34]
  ...
  [ 15  14  16]
  [ 14  13  15]
  [ 13  12  14]]

 [[ 37  35  35]
  [ 35  33  33]
  [ 35  33  33]
  ...
  [ 12  11  13]
  [ 14  13  15]
  [ 15  14  16]]]
