# 读取图片

In [1]:
from PIL import Image
import numpy as np

def read_img(img_path):
    img = Image.open(img_path)
    img_type = type(img)
    img_size = img.size
    img_mat = np.array(img)
    img_shape = img_mat.shape
    return img_type, img_size, img_shape, img_mat

if __name__ == '__main__':
    img_path = 'data/img1.jpg'
    img_type, img_size, img_shape, img_mat = read_img(img_path)
    print('img_type: {}'.format(img_type))
    print('img_size: {}'.format(img_size))
    print('img_shape: {}'.format(img_shape))
    print('img_mat: {}'.format(img_mat))

img_type: <class 'PIL.JpegImagePlugin.JpegImageFile'>
img_size: (2560, 1600)
img_shape: (1600, 2560, 3)
img_mat: [[[176 200 224]
  [176 200 224]
  [176 200 224]
  ...
  [149 178 212]
  [149 178 212]
  [149 178 212]]

 [[176 200 224]
  [176 200 224]
  [176 200 224]
  ...
  [150 179 213]
  [150 179 213]
  [150 179 213]]

 [[176 200 224]
  [176 200 224]
  [176 200 224]
  ...
  [151 180 214]
  [152 181 215]
  [152 181 215]]

 ...

 [[ 28  28  30]
  [ 32  32  34]
  [ 39  39  41]
  ...
  [ 15  13  14]
  [ 11   9  10]
  [  9   7   8]]

 [[ 31  31  33]
  [ 32  32  34]
  [ 34  34  36]
  ...
  [ 16  14  15]
  [ 15  13  14]
  [ 14  12  13]]

 [[ 35  35  37]
  [ 33  33  35]
  [ 33  33  35]
  ...
  [ 13  11  12]
  [ 15  13  14]
  [ 16  14  15]]]


# 保存图片

In [2]:
from PIL import Image
import numpy as np

def save_img(in_path, out_path):
    img = Image.open(in_path)
    img.save(out_path, 'png')
    
if __name__ == '__main__':
    in_path = 'data/img1.jpg'
    out_path = 'save.png'
    save_img(in_path, out_path)