In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
x = x.reshape(-1, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.randn(3, 4)

tensor([[-0.9139,  0.5128, -1.0192,  0.2458],
        [ 2.1249,  0.8520,  0.5393, -0.2686],
        [-0.4542, -0.8432,  0.1039,  1.4413]])

In [10]:
torch.tensor([[2, 3, 5, 2], [3, 7, 4, 7], [3, 7, 8, 4]])

tensor([[2, 3, 5, 2],
        [3, 7, 4, 7],
        [3, 7, 8, 4]])

In [11]:
x = torch.tensor([7., 6, 7, 8])
y = torch.tensor([4, 1, 2, 3])
x+y, x-y, x*y, x/y, x**y

(tensor([11.,  7.,  9., 11.]),
 tensor([3., 5., 5., 5.]),
 tensor([28.,  6., 14., 24.]),
 tensor([1.7500, 6.0000, 3.5000, 2.6667]),
 tensor([2401.,    6.,   49.,  512.]))

In [12]:
torch.exp(x)

tensor([1096.6332,  403.4288, 1096.6332, 2980.9580])

In [13]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[5., 4, 8, 6], [5, 7, 3, 8], [8, 3, 8, 3]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 5.,  4.,  8.,  6.],
         [ 5.,  7.,  3.,  8.],
         [ 8.,  3.,  8.,  3.]]),
 tensor([[ 0.,  1.,  2.,  3.,  5.,  4.,  8.,  6.],
         [ 4.,  5.,  6.,  7.,  5.,  7.,  3.,  8.],
         [ 8.,  9., 10., 11.,  8.,  3.,  8.,  3.]]))

In [14]:
x == y

tensor([[False, False, False, False],
        [False, False, False, False],
        [ True, False, False, False]])

In [15]:
x.sum()

tensor(66.)

In [16]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [17]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [18]:
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [19]:
x[1, 2] = 4
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  4.,  7.],
        [ 8.,  9., 10., 11.]])

In [20]:
x[0:2, :] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [21]:
a = id(y)
y = y + x
id(y) == a

False

In [22]:
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 2547244002496
id(z): 2547244002496


In [23]:
a = id(x)
x += y
print(id(x) == a)
x[:] = x + y
print(id(x) == a)

True
True


In [24]:
a = x.numpy()
b = torch.tensor(a)
type(a), type(b)

(numpy.ndarray, torch.Tensor)

In [25]:
a = torch.arange(6).reshape((2, 3))
b = torch.tensor([[2, 5, 6], [5, 8, 5]])
a < b, a > b

(tensor([[ True,  True,  True],
         [ True,  True, False]]),
 tensor([[False, False, False],
         [False, False, False]]))

In [26]:
a = torch.arange(12).reshape((2, 2, 3))
b = torch.tensor([[1, 1, 1], [1, 1, 1]])
a + b

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])