In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        return x - x.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
y = net(torch.rand(4, 8))
y.mean()

tensor(-1.1642e-09, grad_fn=<MeanBackward0>)

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
        
    def forward(self, x):
        linear = torch.matmul(x, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.5987, -1.0827,  0.9080],
        [-0.3755, -0.3034,  0.2652],
        [-0.0228, -0.2402,  1.2678],
        [-0.7027,  0.4563, -0.1416],
        [-2.1853, -0.0532, -0.6934]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))

tensor([[0.0000, 1.8334, 1.2144],
        [0.0000, 2.0508, 0.5151]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[1.3247],
        [6.6681]])