In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        return x - x.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
y = net(torch.rand(4, 8))
y.mean()

tensor(-1.8626e-09, grad_fn=<MeanBackward0>)

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
        
    def forward(self, x):
        linear = torch.matmul(x, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.2707, -1.9668, -1.1193],
        [ 0.4411, -1.0937,  0.1524],
        [-0.4963, -1.3878, -0.1957],
        [ 1.1502, -0.0172, -0.1367],
        [ 1.0006, -0.6346, -0.7691]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))

tensor([[1.2741, 0.0000, 0.0000],
        [0.0851, 0.0000, 0.0000]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[ 1.5931],
        [35.5811]])