In [1]:
import torch
print(torch.__version__)

1.4.0+cpu


In [2]:
x = torch.empty(5, 3)
x

tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38]])

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.3753, 0.3557, 0.5669],
        [0.9214, 0.0408, 0.2709],
        [0.8261, 0.6869, 0.8670],
        [0.1789, 0.6808, 0.7400],
        [0.7782, 0.9522, 0.6421]])

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-1.1619,  1.0841, -0.1448],
        [-0.0833,  1.2660, -1.8500],
        [-1.7446,  1.1768, -0.1450],
        [-1.0295, -0.7123,  2.9841],
        [ 1.4069,  1.0746, -1.6034]])

In [7]:
x.size()

torch.Size([5, 3])

In [8]:
y = torch.rand(5, 3)
x + y

tensor([[-0.5946,  1.9803,  0.8284],
        [ 0.5677,  2.0008, -1.6082],
        [-0.7883,  1.6623,  0.2071],
        [-0.7033,  0.0227,  3.4241],
        [ 1.8891,  1.5123, -0.7766]])

In [9]:
x[:, 1]

tensor([ 1.0841,  1.2660,  1.1768, -0.7123,  1.0746])

In [11]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [14]:
x = torch.randn(3, 4, requires_grad=True)
x

tensor([[-0.2426, -0.4526, -0.0484, -0.6236],
        [-1.6453, -3.3229, -0.2884,  0.8764],
        [ 1.2029, -0.2976, -1.1579,  0.2199]], requires_grad=True)

In [15]:
x = torch.randn(3, 4)
x.requires_grad=True
x

tensor([[-1.2373, -0.3035, -1.2769,  0.0629],
        [-3.0068, -0.6667, -0.1494,  0.0574],
        [ 0.9499, -0.4870, -1.3028,  1.2649]], requires_grad=True)

In [16]:
b = torch.randn(3, 4, requires_grad=True)
t = x + b

In [17]:
y = t.sum()
y

tensor(-10.9821, grad_fn=<SumBackward0>)

In [18]:
y.backward()

In [19]:
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
x.requires_grad, b.requires_grad, t.requires_grad

(True, True, True)

In [21]:
x = torch.rand(1)
b = torch.rand(1, requires_grad=True)
w = torch.rand(1, requires_grad=True)
y = w * x
z = y + b

In [22]:
x.requires_grad, b.requires_grad, w.requires_grad, y.requires_grad

(False, True, True, True)

In [24]:
x.is_leaf, w.is_leaf, b.is_leaf, y.is_leaf, z.is_leaf

(True, True, True, False, False)

In [34]:
z.backward(retain_graph=True)

In [35]:
w.grad

tensor([2.4877])

In [36]:
b.grad

tensor([4.])

In [38]:
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1, 1)
x_train.shape

(11, 1)

In [39]:
y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1, 1)
y_train.shape

(11, 1)

In [40]:
import torch
import torch.nn as nn

In [42]:
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        out = self.linear(x)
        return out

In [43]:
input_dim = 1
output_dim = 1
model = LinearRegressionModel(input_dim, output_dim)

In [45]:
epochs = 1000
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss()

In [51]:
for epoch in range(epochs):
    epoch += 1
    inputs = torch.from_numpy(x_train)
    labels = torch.from_numpy(y_train)
    
    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    if epoch % 50 == 0:
        print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 50, loss 1.3088163086649729e-06
epoch 100, loss 7.468002536370477e-07
epoch 150, loss 4.257391310602543e-07
epoch 200, loss 2.4301672851834155e-07
epoch 250, loss 1.384578354191035e-07
epoch 300, loss 7.900289489271017e-08
epoch 350, loss 4.508356354904208e-08
epoch 400, loss 2.574675050937003e-08
epoch 450, loss 1.4567398842757484e-08
epoch 500, loss 8.364576586927797e-09
epoch 550, loss 4.74414152407121e-09
epoch 600, loss 2.726611159076242e-09
epoch 650, loss 1.5441957712525323e-09
epoch 700, loss 9.019396896015053e-10
epoch 750, loss 5.243340206462221e-10
epoch 800, loss 2.996581593972536e-10
epoch 850, loss 1.759074552687423e-10
epoch 900, loss 1.0099041047872959e-10
epoch 950, loss 5.929317453690075e-11
epoch 1000, loss 4.0769974202214954e-11


In [52]:
predicted = model(torch.from_numpy(x_train).requires_grad_()).data.numpy()
predicted

array([[ 0.9999883],
       [ 2.99999  ],
       [ 4.9999914],
       [ 6.9999933],
       [ 8.999995 ],
       [10.999997 ],
       [12.999998 ],
       [15.       ],
       [17.000002 ],
       [19.000004 ],
       [21.000006 ]], dtype=float32)

In [55]:
torch.save(model.state_dict(), 'model.pkl')

In [56]:
model.load_state_dict(torch.load('model.pkl'))

<All keys matched successfully>

In [60]:
import torch
import torch.nn as nn
import numpy as np

class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        out = self.linear(x)
        return out

input_dim = 1
output_dim = 1
model = LinearRegressionModel(input_dim, output_dim)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)
criterion = nn.MSELoss()
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

opochs = 1000
for epoch in range(opochs):
    epoch += 1
    inputs = torch.from_numpy(x_train).to(device)
    labels = torch.from_numpy(y_train).to(device)
    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    if epoch % 50 == 0:
        print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 50, loss 0.012757568620145321
epoch 100, loss 0.007276434917002916
epoch 150, loss 0.004150193650275469
epoch 200, loss 0.0023671237286180258
epoch 250, loss 0.0013501342618837953
epoch 300, loss 0.0007700599962845445
epoch 350, loss 0.0004392193804960698
epoch 400, loss 0.00025051136617548764
epoch 450, loss 0.00014288061356637627
epoch 500, loss 8.14949453342706e-05
epoch 550, loss 4.6480916353175417e-05
epoch 600, loss 2.6511546820984222e-05
epoch 650, loss 1.5121012438612524e-05
epoch 700, loss 8.625976988696493e-06
epoch 750, loss 4.919433195027523e-06
epoch 800, loss 2.8058952921128366e-06
epoch 850, loss 1.6010857279979973e-06
epoch 900, loss 9.128908118327672e-07
epoch 950, loss 5.207662638895272e-07
epoch 1000, loss 2.971519563743641e-07


In [61]:
import torch
from torch import tensor

In [62]:
x = tensor(42.)
x

tensor(42.)

In [64]:
x.dim()

0

In [65]:
2*x

tensor(84.)

In [66]:
x.item()

42.0

In [67]:
v = tensor([1.5, -0.5, 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [68]:
v.dim()

1

In [69]:
v.size()

torch.Size([3])

In [70]:
M = tensor([[1., 2.],[3., 4.]])
M

tensor([[1., 2.],
        [3., 4.]])

In [71]:
M.matmul(M)

tensor([[ 7., 10.],
        [15., 22.]])

In [72]:
tensor([1., 0.]).matmul(M)

tensor([1., 2.])

In [73]:
M * M

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [74]:
tensor([1., 2.]).matmul(M)

tensor([ 7., 10.])