In [1]:
import torch

In [2]:
torch.__version__

'1.9.0+cu111'

In [3]:
x=torch.empty(5,3)
x

tensor([[4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38]])

In [4]:
x=torch.rand(5,3)
x

tensor([[0.9294, 0.0360, 0.0462],
        [0.0535, 0.5705, 0.0829],
        [0.2197, 0.6874, 0.0306],
        [0.5658, 0.1835, 0.5217],
        [0.4654, 0.1793, 0.4741]])

In [5]:
x=torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x=torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [7]:
x=x.new_ones(5, 3, dtype=torch.float64)
print(x)
x=torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.3335, 0.6156, 0.8240],
        [0.2983, 0.4727, 0.8456],
        [0.7443, 0.6608, 0.0391],
        [0.7028, 0.8403, 0.4596],
        [0.9618, 0.1248, 0.7923]])


In [8]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [9]:
y = torch.rand(5,3)
print(x+y)

tensor([[1.2188, 0.8549, 1.4315],
        [1.2764, 0.6863, 1.1522],
        [1.2913, 1.2319, 0.8042],
        [1.5479, 1.4619, 1.4453],
        [1.1406, 0.9188, 1.2115]])


In [10]:
print(torch.add(x, y))

tensor([[1.2188, 0.8549, 1.4315],
        [1.2764, 0.6863, 1.1522],
        [1.2913, 1.2319, 0.8042],
        [1.5479, 1.4619, 1.4453],
        [1.1406, 0.9188, 1.2115]])


In [11]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.2188, 0.8549, 1.4315],
        [1.2764, 0.6863, 1.1522],
        [1.2913, 1.2319, 0.8042],
        [1.5479, 1.4619, 1.4453],
        [1.1406, 0.9188, 1.2115]])


In [12]:
y.add_(x)
print(y)

tensor([[1.2188, 0.8549, 1.4315],
        [1.2764, 0.6863, 1.1522],
        [1.2913, 1.2319, 0.8042],
        [1.5479, 1.4619, 1.4453],
        [1.1406, 0.9188, 1.2115]])


In [13]:
y = x[0, :]
y+=1
print(y)
print(x[0, :])

tensor([1.3335, 1.6156, 1.8240])
tensor([1.3335, 1.6156, 1.8240])


In [14]:
y = x.view(15)
z = x.view(-1, 5)
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [15]:
x += 1
print(x)
print(y)

tensor([[2.3335, 2.6156, 2.8240],
        [1.2983, 1.4727, 1.8456],
        [1.7443, 1.6608, 1.0391],
        [1.7028, 1.8403, 1.4596],
        [1.9618, 1.1248, 1.7923]])
tensor([2.3335, 2.6156, 2.8240, 1.2983, 1.4727, 1.8456, 1.7443, 1.6608, 1.0391,
        1.7028, 1.8403, 1.4596, 1.9618, 1.1248, 1.7923])


In [16]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[1.3335, 1.6156, 1.8240],
        [0.2983, 0.4727, 0.8456],
        [0.7443, 0.6608, 0.0391],
        [0.7028, 0.8403, 0.4596],
        [0.9618, 0.1248, 0.7923]])
tensor([2.3335, 2.6156, 2.8240, 1.2983, 1.4727, 1.8456, 1.7443, 1.6608, 1.0391,
        1.7028, 1.8403, 1.4596, 1.9618, 1.1248, 1.7923])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7329])
-0.7328945994377136


In [18]:
x = torch.arange(1,3).view(1,2)
print(x)
y = torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [19]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
y=y+x
print(id(y)==id_before)

False


In [20]:
x = torch.tensor([1,2])
y =torch.tensor([3,4])
id_before=id(y)
y[:]=y+x
print(id(y)==id_before)

True


In [21]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
# torch.add(x, y, out=y)
y.add_(x)
# y+=x
print(id(y)==id_before)

True


In [22]:
a=torch.ones(5)
b=a.numpy()
print(a, b)

a+=1
print(a,b)
b+=1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [23]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
print(a,b)

a+=1
print(a,b)
b+=1
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [24]:
c=torch.tensor(a)
a+=1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [25]:
if torch.cuda.is_available():
    device=torch.device('cuda')
    y=torch.ones_like(x,device=device)
#Tensor
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to('cpu', torch.double))

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)


In [26]:
x=torch.ones(2,2, requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [27]:
y = x+2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [28]:
print(x.is_leaf, y.is_leaf)

True False


In [29]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [30]:
a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [31]:
out.backward()

In [32]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [33]:
w=torch.Tensor([[1]])