In [1]:
import torch
import numpy as np

(0,1)均匀分布

In [2]:
x = torch.rand(3, 4)
x

tensor([[0.7174, 0.1802, 0.6200, 0.7897],
        [0.6101, 0.3694, 0.8741, 0.2504],
        [0.2915, 0.0733, 0.3073, 0.1684]])

正态分布

In [3]:
x = torch.randn(2, 6)
x

tensor([[ 0.4003,  0.2035,  0.2578, -0.6048,  0.1328, -0.6389],
        [ 1.2306, -0.1284,  0.5551,  1.5884, -1.0401,  1.7474]])

全0数组

In [4]:
x = torch.zeros(4, 7)
x

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

全1数组

In [5]:
x = torch.ones((2, 3, 4), dtype=torch.int32)
x

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int32)

查看数据维度

In [6]:
x.size()

torch.Size([2, 3, 4])

In [7]:
x.shape

torch.Size([2, 3, 4])

In [8]:
x.size(1)

3

通过数组创建张量

In [9]:
x = torch.tensor([3, 4, 5], dtype=torch.float64)
x

tensor([3., 4., 5.], dtype=torch.float64)

In [10]:
x.type()

'torch.DoubleTensor'

数据类型转换

In [11]:
x.type(torch.int32)

tensor([3, 4, 5], dtype=torch.int32)

tensor和ndarray类型转换

In [12]:
a = np.random.randn(2, 3)
a

array([[-0.32622684, -1.95070757,  0.66991082],
       [ 0.12507687, -0.49362209,  0.36349421]])

从ndarray转变为tensor

In [13]:
x = torch.from_numpy(a)
x

tensor([[-0.3262, -1.9507,  0.6699],
        [ 0.1251, -0.4936,  0.3635]], dtype=torch.float64)

从tensor转变为ndarray

In [14]:
x.numpy()

array([[-0.32622684, -1.95070757,  0.66991082],
       [ 0.12507687, -0.49362209,  0.36349421]])

In [15]:
x2 = torch.rand(2, 3)
x2

tensor([[0.4887, 0.5209, 0.4725],
        [0.3517, 0.8992, 0.8990]])

向量相加

In [16]:
x + x2

tensor([[ 0.1625, -1.4298,  1.1425],
        [ 0.4768,  0.4056,  1.2625]], dtype=torch.float64)

广播

In [17]:
x2 + 6

tensor([[6.4887, 6.5209, 6.4725],
        [6.3517, 6.8992, 6.8990]])

原来元素没有改变

In [18]:
x.add(x2)

tensor([[ 0.1625, -1.4298,  1.1425],
        [ 0.4768,  0.4056,  1.2625]], dtype=torch.float64)

原来元素发生改变

In [19]:
x.add_(x2)
x.shape

torch.Size([2, 3])

改变张量维度

In [20]:
x.view(3, 2)

tensor([[ 0.1625, -1.4298],
        [ 1.1425,  0.4768],
        [ 0.4056,  1.2625]], dtype=torch.float64)

In [21]:
x.view(-1, 1)

tensor([[ 0.1625],
        [-1.4298],
        [ 1.1425],
        [ 0.4768],
        [ 0.4056],
        [ 1.2625]], dtype=torch.float64)

求平均数

In [22]:
x.mean()

tensor(0.3367, dtype=torch.float64)

求和

In [23]:
x = x.sum()
x

tensor(2.0200, dtype=torch.float64)

返回标量

In [24]:
x.item()

2.01996406414785

张量的自动微分

In [25]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

是否跟踪张量操作

In [26]:
x.requires_grad

True

张量的值

In [27]:
x.data

tensor([[1., 1.],
        [1., 1.]])

张量的梯度

In [28]:
x.grad

是由什么操作得到

In [29]:
x.grad_fn

In [30]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [31]:
y.grad_fn
z = y * y + 8
z

tensor([[17., 17.],
        [17., 17.]], grad_fn=<AddBackward0>)

In [32]:
out = z.mean()
out

tensor(17., grad_fn=<MeanBackward0>)

计算张量的微分

In [33]:
out.backward()
x.grad

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])

In [34]:
x.data

tensor([[1., 1.],
        [1., 1.]])

不跟踪梯度

In [35]:
with torch.no_grad():
    print((x**2).requires_grad)

False


跟踪梯度

In [36]:
(x**2).requires_grad

True

不跟踪梯度（等价于with torch.no_grad():）

In [37]:
y = x.detach()
y

tensor([[1., 1.],
        [1., 1.]])

In [38]:
y.requires_grad

False

如何将张量修改成跟踪梯度

In [39]:
a = torch.tensor([4, 6], dtype=torch.float32)
a.requires_grad

False

In [40]:
a.requires_grad_(True)
a

tensor([4., 6.], requires_grad=True)