In [1]:
import tensorflow as tf


net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4, activation=tf.nn.relu),
    tf.keras.layers.Dense(1)
])

x = tf.random.uniform((2, 4))
net(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.18853128],
       [-0.52353686]], dtype=float32)>

In [2]:
print(net.layers[2].weights)

[<tf.Variable 'dense_1/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[-0.07375336],
       [ 0.50009143],
       [-1.0352844 ],
       [ 0.30132818]], dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]


In [3]:
print(type(net.layers[2].weights[1]))
print(net.layers[2].weights[1])
print(tf.convert_to_tensor(net.layers[2].weights[1]))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>
tf.Tensor([0.], shape=(1,), dtype=float32)


In [4]:
print(net.layers[1].weights)
print(net.get_weights())

[<tf.Variable 'dense/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[-0.23326254,  0.64815444,  0.57666236,  0.38071698],
       [-0.49288696, -0.58452994,  0.54513115, -0.14753205],
       [-0.74428886, -0.4524822 , -0.6107849 , -0.51189643],
       [ 0.00591862,  0.822481  ,  0.31776017, -0.6269317 ]],
      dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]
[array([[-0.23326254,  0.64815444,  0.57666236,  0.38071698],
       [-0.49288696, -0.58452994,  0.54513115, -0.14753205],
       [-0.74428886, -0.4524822 , -0.6107849 , -0.51189643],
       [ 0.00591862,  0.822481  ,  0.31776017, -0.6269317 ]],
      dtype=float32), array([0., 0., 0., 0.], dtype=float32), array([[-0.07375336],
       [ 0.50009143],
       [-1.0352844 ],
       [ 0.30132818]], dtype=float32), array([0.], dtype=float32)]


In [5]:
net.get_weights()[1]

array([0., 0., 0., 0.], dtype=float32)

In [6]:
def block1(name):
    return tf.keras.Sequential([
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(4, activation=tf.nn.relu)
    ], name=name)

def block2():
    net = tf.keras.Sequential()
    for i in range(4):
        net.add(block1(name=f'block-{i}'))
    return net

rgnet = tf.keras.Sequential()
rgnet.add(block2())
rgnet.add(tf.keras.layers.Dense(1))
rgnet(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.07626164],
       [-0.13044663]], dtype=float32)>

In [7]:
print(rgnet.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
sequential_2 (Sequential)    (2, 4)                    80        
_________________________________________________________________
dense_6 (Dense)              (2, 1)                    5         
Total params: 85
Trainable params: 85
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
rgnet.layers[0].layers[1].layers[1].weights[1]

<tf.Variable 'dense_3/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [9]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4, activation=tf.nn.relu, 
        kernel_initializer=tf.random_normal_initializer(mean=0, stddev=0.01),
        bias_initializer=tf.zeros_initializer()),
    tf.keras.layers.Dense(1)])

net(x)
net.weights[0], net.weights[1]

(<tf.Variable 'dense_7/kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[-0.01340874, -0.00546989,  0.00732673, -0.00252811],
        [-0.01348657, -0.00832916,  0.00505453,  0.00765454],
        [-0.00536071,  0.01227327,  0.01024241, -0.02303865],
        [-0.0003635 ,  0.00015053,  0.00455184,  0.0041526 ]],
       dtype=float32)>,
 <tf.Variable 'dense_7/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>)

In [10]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4, activation=tf.nn.relu, 
        kernel_initializer=tf.keras.initializers.Constant(1),
        bias_initializer=tf.zeros_initializer()),
    tf.keras.layers.Dense(1)
])

net(x)
net.weights[0], net.weights[1]

(<tf.Variable 'dense_9/kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Variable 'dense_9/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>)

In [11]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4, activation=tf.nn.relu, 
        kernel_initializer=tf.keras.initializers.GlorotUniform()),
    tf.keras.layers.Dense(1, 
        kernel_initializer=tf.keras.initializers.Constant(1))
])

net(x)
print(net.layers[1].weights[0])
print(net.layers[2].weights[0])

<tf.Variable 'dense_11/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.5990996 ,  0.37844223, -0.23513567,  0.5874755 ],
       [ 0.7487337 , -0.8064693 , -0.65180224, -0.6089685 ],
       [ 0.39980096, -0.7179396 , -0.43755868, -0.5307523 ],
       [ 0.68102366, -0.03574586, -0.30264342,  0.18043691]],
      dtype=float32)>
<tf.Variable 'dense_12/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>


In [12]:
class MyInit(tf.keras.initializers.Initializer):
    def __call__(self, shape, dtype=None):
        data = tf.random.uniform(shape, -10, 10, dtype=dtype)
        factor = (tf.abs(data) > 5)
        factor = tf.cast(factor, tf.float32)
        return data * factor
    
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4, activation=tf.nn.relu, 
        kernel_initializer=MyInit()),
    tf.keras.layers.Dense(1)
])

net(x)
print(net.layers[1].weights[0])

<tf.Variable 'dense_13/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.       ,  0.       ,  0.       , -6.2957096],
       [-0.       ,  6.982832 , -5.6562853, -6.4260173],
       [-6.539657 , -6.4296865,  0.       , -0.       ],
       [-6.8829727,  9.42771  ,  6.0351677, -8.888332 ]], dtype=float32)>


In [13]:
net.layers[1].weights[0][:].assign(net.layers[1].weights[0] + 1)
net.layers[1].weights[0][0, 0].assign(42)
net.layers[1].weights[0]

<tf.Variable 'dense_13/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[42.       ,  1.       ,  1.       , -5.2957096],
       [ 1.       ,  7.982832 , -4.6562853, -5.4260173],
       [-5.539657 , -5.4296865,  1.       ,  1.       ],
       [-5.8829727, 10.42771  ,  7.0351677, -7.8883324]], dtype=float32)>

In [14]:
shared = tf.keras.layers.Dense(4, activation=tf.nn.relu)
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    shared,
    shared,
    tf.keras.layers.Dense(1)
])

net(x)
print(len(net.layers) == 3)

True
