In [1]:
import tensorflow as tf


def pool2d(x, pool_size, mode='max'):
    p_h, p_w = pool_size
    y = tf.Variable(tf.zeros((x.shape[0] - p_h + 1, x.shape[1] - p_w +1)))
    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            if mode == 'max':
                y[i, j].assign(tf.reduce_max(x[i: i + p_h, j: j + p_w]))
            elif mode =='avg':
                y[i, j].assign(tf.reduce_mean(x[i: i + p_h, j: j + p_w]))
    return y

In [2]:
x = tf.constant([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(x, (2, 2))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[4., 5.],
       [7., 8.]], dtype=float32)>

In [3]:
pool2d(x, (2, 2), 'avg')

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [4]:
x = tf.reshape(tf.range(16, dtype=tf.float32), (1, 4, 4, 1))
x

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.]],

        [[ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.]],

        [[12.],
         [13.],
         [14.],
         [15.]]]], dtype=float32)>

In [5]:
pool2d = tf.keras.layers.MaxPool2D(pool_size=[3, 3])
pool2d(x)

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[10.]]]], dtype=float32)>

In [6]:
pool2d = tf.keras.layers.MaxPool2D(pool_size=[3, 3], padding='same',
                                   strides=2)
pool2d(x)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[10.],
         [11.]],

        [[14.],
         [15.]]]], dtype=float32)>

In [7]:
pool2d = tf.keras.layers.MaxPool2D(pool_size=[2, 3], padding='same',
                                   strides=(2, 3))
pool2d(x)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 5.],
         [ 7.]],

        [[13.],
         [15.]]]], dtype=float32)>

In [8]:
x = tf.reshape(tf.stack([x, x+1], 0), (1, 2, 4, 4))

In [9]:
pool2d = tf.keras.layers.MaxPool2D(3, padding='same', strides=2)
pool2d(x)

<tf.Tensor: shape=(1, 1, 2, 4), dtype=float32, numpy=
array([[[[ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]]], dtype=float32)>