In [1]:
import numpy as np
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [2]:
print(a)

[0 1 2 3]


In [3]:
type(a)

numpy.ndarray

In [4]:
a[0]

0

In [5]:
print(a[1],a[2],a[3])

1 2 3


In [6]:
a[0:3]

array([0, 1, 2])

In [7]:
a[:3]

array([0, 1, 2])

In [8]:
a[0:]

array([0, 1, 2, 3])

In [9]:
a.ndim

1

In [10]:
a.shape

(4,)

In [11]:
a.size

4

In [12]:
b =np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
b.ndim

2

In [14]:
b.shape

(3, 4)

In [15]:
b.size

12

In [16]:
b[0]

array([0, 1, 2, 3])

In [17]:
b[1]

array([4, 5, 6, 7])

In [18]:
b[2]

array([ 8,  9, 10, 11])

In [19]:
b[0][0]

0

In [20]:
b[0,0]

0

In [21]:
b[0][1]

1

In [22]:
b[0,1]

1

In [23]:
t =np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],[[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
t

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
t.ndim

3

In [25]:
t.shape

(2, 3, 4)

In [26]:
t.size

24

In [27]:
t[0].ndim

2

In [28]:
t[0].shape

(3, 4)

In [29]:
t[0].size

12

In [30]:
t[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
t[0][0]

array([0, 1, 2, 3])

In [32]:
t[0,0]

array([0, 1, 2, 3])

In [33]:
t[0,0].shape

(4,)

In [34]:
t[0][0].size

4

In [35]:
t[0,0,0]

0

In [36]:
t[0][0][0]

0

In [37]:
a = np.array([0,1,2,3],dtype=np.int64)
a

array([0, 1, 2, 3], dtype=int64)

In [38]:
a.dtype

dtype('int64')

In [39]:
a.itemsize

8

In [43]:
b = np.array([0,1,2,3],dtype=np.int32)
b.itemsize

4

In [45]:
c = np.array([1.2,3.5,5.1])
c.dtype

dtype('float64')

In [46]:
np.arange(4)

array([0, 1, 2, 3])

In [49]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [50]:
np.ones((2,3),dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [51]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [52]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [55]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [59]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [60]:
np.logspace(1,5,5,base=2)

array([ 2.,  4.,  8., 16., 32.])

In [64]:
np.logspace(1,8,4,base=2)

array([  2.        ,  10.0793684 ,  50.79683366, 256.        ])

In [66]:
2**8

256

In [68]:
np.logspace(2,6,3,base=2)

array([ 4., 16., 64.])

In [79]:
list1=[[1,1,1],[1,1,1],[1,1,1]]
arr1=np.array(list1)
arr2=np.asarray(list1)
list1[0][0]=3

In [80]:
list1

[[3, 1, 1], [1, 1, 1], [1, 1, 1]]

In [81]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [82]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [83]:
arr1=np.ones((3,3))
arr2=np.array(arr1)
arr3=np.asarray(arr1)
arr1[0][0]=3

In [84]:
arr1

array([[3., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [85]:
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
arr3

array([[3., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
b=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
b[0]

array([0, 1, 2, 3])

In [89]:
b[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [90]:
b[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [91]:
b[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [92]:
b[0:2, 1:3]

array([[1, 2],
       [5, 6]])

In [93]:
b[:,0]

array([0, 4, 8])

In [94]:
t=np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],[[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
t

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [95]:
t[:,:,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [96]:
t[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [97]:
b = np.arange(12)

In [98]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
b.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [101]:
b.resize(3,4)

In [102]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
b = np.arange(12)

In [104]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [108]:
b.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [109]:
b = np.arange(12).reshape(3,4)

In [110]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
t = np.arange(24).reshape(2,3,4)
t

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [112]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
b.reshape(-1).ndim

1

In [119]:
a=np.array([0,1,2,3])
b=np.array([2,3,4,5])
a+b

array([2, 4, 6, 8])

In [120]:
d = np.array([1,2])
a+d

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [122]:
a=np.array([0,1,2,3])
b=np.array([[2,3,4,5],[1,2,3,4],[5,6,7,8]])
a+b

array([[ 2,  4,  6,  8],
       [ 1,  3,  5,  7],
       [ 5,  7,  9, 11]])

In [123]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
b**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [126]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
C = A*B
C

array([[2, 0],
       [0, 4]])

In [127]:
np.matmul(A, B)

array([[5, 4],
       [3, 4]])

In [128]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [129]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [130]:
A

array([[1, 1],
       [0, 1]])

In [131]:
np.transpose(A)

array([[1, 0],
       [1, 1]])

In [132]:
B

array([[2, 0],
       [3, 4]])

In [133]:
np.transpose(B)

array([[2, 3],
       [0, 4]])

In [134]:
np.linalg.inv(A)

array([[ 1., -1.],
       [ 0.,  1.]])

In [140]:
b = np.linalg.inv(B)

In [141]:
B

array([[2, 0],
       [3, 4]])

In [142]:
b

array([[ 0.5  ,  0.   ],
       [-0.375,  0.25 ]])

In [143]:
b.dot(B)

array([[1., 0.],
       [0., 1.]])

In [144]:
np.matmul(B,b)

array([[1., 0.],
       [0., 1.]])

In [145]:
B.dot(b)

array([[1., 0.],
       [0., 1.]])

In [147]:
a=np.arange(4)
np.sum(a)

6

In [149]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
np.sum(b)

66

In [151]:
np.sum(b, axis=1)

array([ 6, 22, 38])

In [152]:
np.sum(b, axis=0)

array([12, 15, 18, 21])

In [153]:
t = np.arange(24).reshape(2,3,4)
t

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [154]:
np.sum(t, axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [155]:
np.sum(t, axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [156]:
np.sum(t, axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [157]:
d=np.logspace(1,4,4,base=2)
d

array([ 2.,  4.,  8., 16.])

In [158]:
np.sqrt(d)

array([1.41421356, 2.        , 2.82842712, 4.        ])

In [159]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.stack((x,y), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
np.stack((x,y),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [161]:
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [169]:
x,y = np.mgrid[1:4:1, 2:16:2]

In [170]:
x,y

(array([[1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3]]), array([[ 2,  4,  6,  8, 10, 12, 14],
        [ 2,  4,  6,  8, 10, 12, 14],
        [ 2,  4,  6,  8, 10, 12, 14]]))

In [171]:
x

array([[1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3]])

In [172]:
y

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 2,  4,  6,  8, 10, 12, 14]])

In [174]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
n = np.array([[10,20,30],[40,50,60],[70,80,90]])
np.stack((m,n), axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [175]:
np.stack((m,n), axis=0).shape

(2, 3, 3)

In [176]:
np.stack((m,n),axis=1)

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 4,  5,  6],
        [40, 50, 60]],

       [[ 7,  8,  9],
        [70, 80, 90]]])

In [177]:
np.stack((m,n),axis=1).shape

(3, 2, 3)

In [178]:
np.stack((m,n),axis=2)

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]]])

In [179]:
np.stack((m,n),axis=2).shape

(3, 3, 2)

In [182]:
a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([8,9,10,11])
np.stack((a,b,c),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
np.stack((a,b,c), axis=1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [185]:
a = np.mat('1 2 3; 4 5 6')
a

matrix([[1, 2, 3],
        [4, 5, 6]])

In [186]:
b = np.mat([[1,2,3],[4,5,6]])
b

matrix([[1, 2, 3],
        [4, 5, 6]])

In [187]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [189]:
m = np.mat(a)
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [190]:
type(a)

numpy.ndarray

In [191]:
type(m)

numpy.matrix

In [192]:
m.ndim

2

In [193]:
m.shape

(2, 3)

In [194]:
m.size

6

In [195]:
m.dtype

dtype('int32')

In [196]:
a1 = np.mat([[0,1],[2,3]])
a2 = np.mat([[1,1],[2,0]])
a3 = a1*a2
a3

matrix([[2, 0],
        [8, 2]])

In [197]:
n = np.mat([[1,2],[-1,-3]])
n

matrix([[ 1,  2],
        [-1, -3]])

In [198]:
n.T

matrix([[ 1, -1],
        [ 2, -3]])

In [199]:
n.I

matrix([[ 3.,  2.],
        [-1., -1.]])

In [201]:
n*n.I

matrix([[1., 0.],
        [0., 1.]])

In [202]:
n.I*n

matrix([[1., 0.],
        [0., 1.]])

In [203]:
a = np.array([[1,2,3],[4,5,6]])
m = np.mat(a)
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [204]:
m.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [205]:
m.I

matrix([[-0.94444444,  0.44444444],
        [-0.11111111,  0.11111111],
        [ 0.72222222, -0.22222222]])

In [206]:
np.random.rand(2,3)

array([[0.09125553, 0.72692217, 0.47502648],
       [0.67645985, 0.8220757 , 0.37591318]])

In [207]:
np.random.rand()

0.925810287763485

In [208]:
np.random.uniform(1,5,(2,3))

array([[4.64144895, 3.02473139, 2.70174512],
       [4.19264889, 3.75635329, 2.84755054]])

In [209]:
np.random.randint(1,5,(3,2))

array([[4, 2],
       [4, 4],
       [1, 2]])

In [210]:
np.random.randn(2,3)

array([[ 1.15060708,  0.16907161, -0.18177856],
       [ 0.05778396, -0.83339471, -0.25665764]])

In [211]:
np.random.normal(0,1,(3,2))

array([[-0.09077109, -0.75171881],
       [ 0.43472483,  1.20799861],
       [-1.61672491,  0.29289297]])

In [212]:
np.random.seed(612)
np.random.rand(2,3)

array([[0.14347163, 0.49589878, 0.95454587],
       [0.13751674, 0.85456667, 0.42853136]])

In [214]:
np.random.seed(612)
np.random.rand(2,3)

array([[0.14347163, 0.49589878, 0.95454587],
       [0.13751674, 0.85456667, 0.42853136]])

In [215]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [218]:
np.random.shuffle(arr)
arr

array([5, 1, 4, 0, 3, 2, 8, 9, 6, 7])

In [219]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [220]:
np.random.shuffle(b)
b

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 3,  4,  5]])