In [1]:
import cv2 as cv
import numpy as np


def video_demo():
    capture = cv.VideoCapture(0)  #读取第几个摄像头
    while True:
        ret, frame = capture.read()
        frame = cv.flip(frame, 1)  #左右翻转
        cv.imshow('videv', frame)
        c = cv.waitKey(50)
        if c == 27:
            break

def get_image_info(image):
    print(type(image))
    print(image.shape)
    print(image.size)
    print(image.dtype)
    pixel_data = np.array(image)
    print(pixel_data)


src = cv.imread('../../data/input.png')
cv.namedWindow('input image', cv.WINDOW_AUTOSIZE)
cv.imshow('input image', src)
get_image_info(src)
# video_demo()

gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)
cv.imwrite('./result.png', gray)
cv.waitKey(0)
cv.destroyAllWindows()

<class 'numpy.ndarray'>
(478, 640, 3)
917760
uint8
[[[239 225 227]
  [239 225 227]
  [239 225 227]
  ...
  [238 220 221]
  [238 220 221]
  [239 221 222]]

 [[239 225 227]
  [239 225 227]
  [239 225 227]
  ...
  [238 220 221]
  [238 220 221]
  [239 221 222]]

 [[239 225 227]
  [239 225 227]
  [239 225 227]
  ...
  [238 220 221]
  [238 220 221]
  [239 221 222]]

 ...

 [[232 212 217]
  [233 213 218]
  [234 214 219]
  ...
  [231 210 209]
  [231 210 209]
  [231 210 209]]

 [[232 212 217]
  [233 213 218]
  [234 214 219]
  ...
  [231 210 209]
  [231 210 209]
  [231 210 209]]

 [[232 212 217]
  [233 213 218]
  [234 214 219]
  ...
  [231 210 209]
  [231 210 209]
  [231 210 209]]]
